name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    env:
      KUBECONFIG: $HOME/.kube/custom-config  # ✅ Force kubectl to use your kubeconfig

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mlops-sales:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops-sales:latest

      # -----------------------------
      # Deploy to Kubernetes
      # -----------------------------

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $KUBECONFIG

      - name: Verify Kubernetes Context
        run: kubectl config get-contexts

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get svc
